language: rust
script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace
  - cargo doc


deploy:
  provider: pages
  skip_cleanup: true
  local_dir: target/doc
  github_token: $GH_REPO_TOKEN
  on:
    branch: main