language: rust
jobs:
  include:
    - stage: Build
      script: 
        - echo "Building project"
        - cargo build --verbose --workspace
# Running tests
    - stage: Test
      script: 
        - echo "Runnning tests"
        - cargo test --verbose --workspace --release
        - cargo doc --no-deps --release
# Lint checks. Block all warnings too
    - stage: Lint checks
      script:
        - cargo clippy --verbose --all -- -D warnings
# Release on github pages
    - stage: GitHub Release
      script: 
        - echo "Deploying to GitHub releases ..."
        - cargo build --verbose --workspace --release
        - cargo test --verbose --workspace --release
        - cargo doc --no-deps --release 
      deploy:
        provider: pages
        api_key: $GH_REPO_TOKEN
        skip_cleanup: true
        local_dir: target/doc/
        on:
          branch: main
