language: rust
script:
  - cargo build --verbose --workspace --release
  - cargo test --verbose --workspace
  - cargo doc --no-deps --release


deploy:
  provider: pages
  skip_cleanup: true
  local_dir: target/doc/
  github_token: $GH_REPO_TOKEN
  on:
    branch: main