[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Jaskirat Singh <jaskiratsingh1208@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.8"
rand = "0.8.3"